In [1]:
import pandas as pd
import numpy as np

In [2]:
ft = pd.read_csv('data/fortune1000.csv')
ft

,Company,Revenues,Profits,Employees,Sector,Industry
0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
1,Exxon Mobil,244363.0,19710.0,71200,Energy,Petroleum Refining
2,Berkshire Hathaway,242137.0,44940.0,377000,Financials,Insurance: Property and Casualty (Stock)
3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
4,UnitedHealth Group,201159.0,10558.0,260000,Health Care,Health Care: Insurance and Managed Care
...,...,...,...,...,...,...
995,SiteOne Landscape Supply,1862.0,54.6,3664,Wholesalers,Wholesalers: Diversified
996,Charles River Laboratories Intl,1858.0,123.4,11800,Health Care,Health Care: Pharmacy and Other Services
997,CoreLogic,1851.0,152.2,5900,Business Services,Financial Data Services
998,Ensign Group,1849.0,40.5,21301,Health Care,Health Care: Medical Facilities
999,HCP,1848.0,414.2,190,Financials,Real estate

In [4]:
ft[ft['Sector'] == 'Technology']

,Company,Revenues,Profits,Employees,Sector,Industry
3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
21,Alphabet,110855.0,12662.0,80110,Technology,Internet Services and Retailing
29,Microsoft,89950.0,21204.0,124000,Technology,Computer Software
33,IBM,79139.0,5753.0,397800,Technology,Information Technology Services
34,Dell Technologies,78660.0,-3728.0,145000,Technology,"Computers, Office Equipment"
...,...,...,...,...,...,...
969,Cadence Design Systems,1943.0,204.1,7214,Technology,Computer Software
970,Nuance Communications,1939.0,-151.0,11600,Technology,Computer Software
973,ServiceNow,1933.0,-149.1,6222,Technology,Computer Software
983,MKS Instruments,1916.0,339.1,4923,Technology,Semiconductors and Other Electronic Components
991,VeriFone Systems,1871.0,-173.8,5600,Technology,Financial Data Services

In [6]:
ft[ft['Sector'] == 'Technology'].mean(numeric_only=True)

Revenues     13347.789320
Profits       1743.959804
Employees    31036.961165
dtype: float64

In [8]:
sectors = ft.groupby('Sector')
sectors

In [9]:
sectors.size()

Sector
Aerospace & Defense               25
Apparel                           14
Business Services                 53
Chemicals                         33
Energy                           107
Engineering & Construction        27
Financials                       155
Food &  Drug Stores               12
Food, Beverages & Tobacco         37
Health Care                       71
Hotels, Restaurants & Leisure     26
Household Products                28
Industrials                       49
Materials                         45
Media                             25
Motor Vehicles & Parts            19
Retailing                         77
Technology                       103
Telecommunications                10
Transportation                    40
Wholesalers                       44
dtype: int64

In [10]:
len(sectors)

21

In [12]:
sectors.groups

{'Aerospace & Defense': [26, 50, 58, 98, 117, 118, 207, 224, 275, 380, 404, 406, 414, 540, 660, 661, 806, 829, 884, 930, 954, 955, 959, 975, 988], 'Apparel': [88, 241, 331, 420, 432, 526, 529, 554, 587, 678, 766, 774, 835, 861], 'Business Services': [142, 160, 187, 199, 201, 221, 235, 242, 253, 295, 325, 358, 364, 423, 462, 465, 486, 493, 497, 499, 502, 510, 528, 567, 577, 584, 591, 599, 604, 618, 649, 686, 691, 692, 700, 702, 712, 720, 738, 744, 771, 802, 810, 825, 879, 888, 894, 895, 898, 905, 922, 972, 997], 'Chemicals': [46, 189, 190, 198, 214, 263, 281, 309, 344, 351, 381, 447, 450, 454, 527, 593, 623, 648, 671, 672, 679, 704, 722, 740, 790, 836, 865, 872, 908, 932, 958, 963, 978], 'Energy': [1, 12, 27, 30, 40, 63, 89, 90, 91, 94, 104, 114, 124, 125, 134, 145, 166, 167, 175, 184, 205, 212, 213, 217, 218, 219, 222, 231, 232, 243, 248, 254, 256, 265, 268, 269, 270, 273, 307, 313, 326, 333, 335, 343, 352, 363, 371, 379, 383, 384, 387, 428, 437, 452, 456, 488, 490, 496, 498, 500, 517, 534, 537, 559, 563, 582, 603, 617, 635, 638, 639, 647, 653, 668, 681, 682, 689, 708, 719, 723, 739, 768, 791, 798, 805, 812, 816, 818, 820, 826, 844, 859, 860, 866, 869, 885, 890, 901, 917, 934, ...], 'Engineering & Construction': [152, 163, 210, 229, 296, 315, 338, 340, 367, 427, 443, 479, 541, 569, 588, 615, 705, 736, 737, 764, 779, 815, 841, 852, 962, 982, 986], 'Financials': [2, 19, 20, 23, 25, 31, 35, 37, 42, 51, 59, 65, 66, 67, 68, 69, 78, 83, 85, 92, 99, 100, 102, 103, 105, 111, 121, 135, 136, 155, 164, 172, 174, 204, 206, 209, 211, 216, 233, 236, 238, 240, 249, 251, 252, 258, 262, 266, 298, 301, 302, 306, 310, 312, 329, 336, 342, 347, 355, 365, 368, 374, 375, 377, 397, 411, 412, 418, 430, 434, 436, 439, 440, 449, 453, 457, 459, 461, 463, 466, 468, 469, 475, 476, 482, 483, 485, 492, 501, 513, 514, 533, 539, 543, 562, 570, 572, 576, 579, 581, ...], 'Food &  Drug Stores': [16, 18, 52, 87, 93, 179, 549, 552, 600, 667, 839, 941], 'Food, Beverages & Tobacco': [44, 47, 79, 86, 95, 107, 113, 116, 153, 181, 215, 225, 274, 320, 322, 357, 361, 378, 382, 385, 417, 445, 477, 480, 511, 538, 575, 611, 628, 633, 683, 694, 717, 734, 759, 900, 937], 'Health Care': [4, 6, 24, 28, 36, 48, 55, 56, 60, 62, 72, 77, 109, 110, 115, 128, 129, 144, 146, 151, 159, 161, 169, 178, 197, 223, 239, 244, 250, 267, 282, 285, 303, 327, 360, 366, 389, 415, 472, 474, 503, 506, 518, 542, 555, 560, 602, 605, 655, 669, 673, 718, 724, 742, 753, 754, 782, 795, 830, 845, 915, 921, 925, 935, 936, 939, 956, 960, 994, 996, 998], 'Hotels, Restaurants & Leisure': [126, 130, 131, 226, 279, 323, 395, 396, 446, 471, 478, 535, 548, 556, 583, 713, 714, 721, 741, 775, 817, 851, 891, 903, 965, 984], 'Household Products': [41, 162, 183, 195, 227, 257, 314, 370, 372, 421, 467, 484, 508, 512, 532, 608, 622, 727, 778, 794, 821, 875, 881, 882, 893, 912, 946, 967], 'Industrials': [17, 64, 76, 96, 101, 139, 148, 154, 177, 203, 255, 292, 341, 346, 359, 413, 419, 444, 546, 571, 601, 616, 619, 620, 626, 627, 631, 634, 664, 687, 730, 731, 750, 776, 803, 813, 827, 850, 853, 854, 857, 864, 878, 887, 938, 943, 951, 966, 981], 'Materials': [123, 150, 193, 245, 261, 276, 304, 311, 337, 393, 398, 399, 403, 409, 426, 435, 441, 455, 460, 516, 522, 524, 564, 594, 595, 596, 606, 609, 614, 624, 641, 662, 663, 685, 695, 707, 729, 756, 781, 786, 833, 837, 945, 957, 974], 'Media': [54, 97, 108, 196, 220, 289, 349, 376, 405, 408, 451, 592, 645, 650, 654, 710, 715, 728, 735, 767, 785, 819, 847, 961, 993], 'Motor Vehicles & Parts': [9, 10, 147, 186, 259, 288, 300, 319, 391, 392, 448, 643, 699, 716, 758, 886, 889, 920, 940], 'Retailing': [0, 7, 14, 22, 38, 39, 71, 84, 119, 122, 133, 137, 138, 156, 171, 173, 180, 182, 208, 230, 234, 247, 271, 272, 277, 278, 280, 287, 293, 294, 297, 316, 321, 328, 332, 334, 339, 362, 390, 422, 424, 433, 438, 458, 464, 470, 504, 507, 509, 545, 547, 580, 589, 610, 612, 621, 644, 665, 680, 698, 732, 745, 746, 770, 777, 792, 822, 846, 855, 856, 858, 880, 909, 926, 971, 989, 992], 'Technology': [3, 21, 29, 33, 34, 45, 57, 61, 75, 81, 106, 132, 143, 149, 157, 158, 188, 191, 194, 200, 228, 260, 284, 290, 291, 305, 308, 353, 373, 388, 400, 402, 410, 416, 431, 442, 481, 491, 494, 505, 515, 519, 523, 525, 536, 544, 550, 551, 553, 557, 558, 573, 578, 585, 586, 597, 636, 646, 656, 666, 674, 696, 697, 703, 709, 726, 752, 755, 763, 769, 780, 783, 787, 788, 797, 799, 807, 823, 824, 828, 834, 842, 843, 849, 862, 868, 871, 874, 876, 892, 897, 902, 919, 924, 927, 931, 944, 948, 969, 970, ...], 'Telecommunications': [8, 15, 32, 73, 165, 202, 324, 473, 520, 907], 'Transportation': [43, 49, 70, 74, 80, 140, 141, 185, 192, 264, 283, 354, 386, 394, 401, 407, 487, 495, 530, 531, 566, 598, 632, 637, 675, 688, 706, 762, 793, 801, 814, 848, 904, 906, 914, 918, 928, 933, 947, 968], 'Wholesalers': [5, 11, 13, 53, 82, 112, 120, 127, 168, 170, 176, 237, 246, 286, 299, 317, 318, 330, 345, 348, 350, 356, 369, 425, 429, 489, 521, 561, 565, 568, 574, 642, 652, 670, 684, 748, 757, 773, 800, 809, 870, 910, 942, 995]}

In [13]:
sectors.first()

,Company,Revenues,Profits,Employees,Industry
Sector,,,,,
Aerospace & Defense,Boeing,93392.0,8197.0,140800,Aerospace and Defense
Apparel,Nike,34350.0,4240.0,74400,Apparel
Business Services,ManpowerGroup,21034.0,545.4,29000,Temporary Help
Chemicals,DowDuPont,62683.0,1460.0,98000,Chemicals
Energy,Exxon Mobil,244363.0,19710.0,71200,Petroleum Refining
Engineering & Construction,Fluor,19521.0,191.4,56706,"Engineering, Construction"
Financials,Berkshire Hathaway,242137.0,44940.0,377000,Insurance: Property and Casualty (Stock)
Food & Drug Stores,Kroger,122662.0,1907.0,449000,Food and Drug Stores
"Food, Beverages & Tobacco",PepsiCo,63525.0,4857.0,263000,Food Consumer Products
Health Care,UnitedHealth Group,201159.0,10558.0,260000,Health Care: Insurance and Managed Care
"Hotels, Restaurants & Leisure",Marriott International,22894.0,1372.0,177000,"Hotels, Casinos, Resorts"
Household Products,Procter & Gamble,66217.0,15326.0,95000,Household and Personal Products
Industrials,General Electric,122274.0,-5786.0,313000,Industrial Machinery
Materials,International Paper,23302.0,2144.0,56000,"Packaging, Containers"
Media,Disney,55137.0,8980.0,199000,Entertainment
Motor Vehicles & Parts,General Motors,157311.0,-3864.0,180000,Motor Vehicles and Parts
Retailing,Walmart,500343.0,9862.0,2300000,General Merchandisers
Technology,Apple,229234.0,48351.0,123000,"Computers, Office Equipment"
Telecommunications,AT&T,160546.0,29450.0,254000,Telecommunications
Transportation,UPS,65872.0,4910.0,346415,"Mail, Package, and Freight Delivery"
Wholesalers,McKesson,198533.0,5070.0,64500,Wholesalers: Health Care

In [14]:
sectors.last()

,Company,Revenues,Profits,Employees,Industry
Sector,,,,,
Aerospace & Defense,Aerojet Rocketdyne Holdings,1877.0,-9.2,5157,Aerospace and Defense
Apparel,Wolverine World Wide,2350.0,0.3,3700,Apparel
Business Services,CoreLogic,1851.0,152.2,5900,Financial Data Services
Chemicals,Stepan,1925.0,91.6,2096,Chemicals
Energy,Superior Energy Services,1874.0,-205.9,6400,"Oil and Gas Equipment, Services"
Engineering & Construction,TopBuild,1906.0,158.1,8400,"Engineering, Construction"
Financials,HCP,1848.0,414.2,190,Real estate
Food & Drug Stores,Freds,2064.0,-140.3,7324,Food and Drug Stores
"Food, Beverages & Tobacco",Universal,2071.0,106.3,24000,Tobacco
Health Care,Ensign Group,1849.0,40.5,21301,Health Care: Medical Facilities
"Hotels, Restaurants & Leisure",Vail Resorts,1907.0,210.6,20150,"Hotels, Casinos, Resorts"
Household Products,ACCO Brands,1949.0,131.7,6620,"Home Equipment, Furnishings"
Industrials,Rexnord,1918.0,74.1,8000,Industrial Machinery
Materials,Summit Materials,1933.0,121.8,6000,"Building Materials, Glass"
Media,Tribune Media,1867.0,194.1,6000,Entertainment
Motor Vehicles & Parts,Tower International,2066.0,47.6,7600,Motor Vehicles and Parts
Retailing,Childrens Place,1870.0,84.7,9800,Specialty Retailers: Apparel
Technology,VeriFone Systems,1871.0,-173.8,5600,Financial Data Services
Telecommunications,Zayo Group Holdings,2200.0,85.7,3794,Telecommunications
Transportation,Echo Global Logistics,1943.0,12.6,2453,Transportation and Logistics
Wholesalers,SiteOne Landscape Supply,1862.0,54.6,3664,Wholesalers: Diversified

In [16]:
sectors.nth(3)

,Company,Revenues,Profits,Employees,Sector,Industry
22,Home Depot,100904.0,8630.0,413000,Retailing,Specialty Retailers: Other
23,Bank of America Corp.,100264.0,18232.0,209376,Financials,Commercial Banks
28,Anthem,90040.0,3842.8,56000,Health Care,Health Care: Insurance and Managed Care
30,Valero Energy,88407.0,4065.0,10015,Energy,Petroleum Refining
33,IBM,79139.0,5753.0,397800,Technology,Information Technology Services
53,Sysco,55371.0,1142.5,66500,Wholesalers,Wholesalers: Food and Grocery
73,Charter Communications,41581.0,9895.0,94800,Telecommunications,Telecommunications
74,Delta Air Lines,41244.0,3577.0,86564,Transportation,Airlines
86,Coca-Cola,35410.0,1248.0,61800,"Food, Beverages & Tobacco",Beverages
87,Publix Super Markets,34837.0,2291.9,193000,Food & Drug Stores,Food and Drug Stores
96,3M,31657.0,4858.0,91536,Industrials,Miscellaneous
98,General Dynamics,30973.0,2912.0,98600,Aerospace & Defense,Aerospace and Defense
186,Goodyear Tire & Rubber,15377.0,346.0,64000,Motor Vehicles & Parts,Motor Vehicles and Parts
195,Newell Brands,14742.0,2748.8,49000,Household Products,"Home Equipment, Furnishings"
196,CBS,14710.0,357.0,14715,Media,Entertainment
198,Monsanto,14640.0,2260.0,21900,Chemicals,Chemicals
199,Aramark,14604.0,373.9,215000,Business Services,Diversified Outsourcing Services
226,Las Vegas Sands,12882.0,2806.0,50500,"Hotels, Restaurants & Leisure","Hotels, Casinos, Resorts"
229,Lennar,12646.0,810.5,9111,Engineering & Construction,Homebuilders
245,United States Steel,12250.0,387.0,29200,Materials,Metals
420,Ralph Lauren,6653.0,-99.3,18250,Apparel,Apparel

In [17]:
sectors.head(2)

,Company,Revenues,Profits,Employees,Sector,Industry
0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
1,Exxon Mobil,244363.0,19710.0,71200,Energy,Petroleum Refining
2,Berkshire Hathaway,242137.0,44940.0,377000,Financials,Insurance: Property and Casualty (Stock)
3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
4,UnitedHealth Group,201159.0,10558.0,260000,Health Care,Health Care: Insurance and Managed Care
5,McKesson,198533.0,5070.0,64500,Wholesalers,Wholesalers: Health Care
6,CVS Health,184765.0,6622.0,203000,Health Care,Health Care: Pharmacy and Other Services
7,Amazon.com,177866.0,3033.0,566000,Retailing,Internet Services and Retailing
8,AT&T,160546.0,29450.0,254000,Telecommunications,Telecommunications
9,General Motors,157311.0,-3864.0,180000,Motor Vehicles & Parts,Motor Vehicles and Parts
10,Ford Motor,156776.0,7602.0,202000,Motor Vehicles & Parts,Motor Vehicles and Parts
11,AmerisourceBergen,153144.0,364.5,19500,Wholesalers,Wholesalers: Health Care
12,Chevron,134533.0,9195.0,51900,Energy,Petroleum Refining
15,Verizon,126034.0,30101.0,155400,Telecommunications,Telecommunications
16,Kroger,122662.0,1907.0,449000,Food & Drug Stores,Food and Drug Stores
17,General Electric,122274.0,-5786.0,313000,Industrials,Industrial Machinery
18,Walgreens Boots Alliance,118214.0,4078.0,290000,Food & Drug Stores,Food and Drug Stores
19,JPMorgan Chase,113899.0,24441.0,252539,Financials,Commercial Banks
21,Alphabet,110855.0,12662.0,80110,Technology,Internet Services and Retailing
26,Boeing,93392.0,8197.0,140800,Aerospace & Defense,Aerospace and Defense
41,Procter & Gamble,66217.0,15326.0,95000,Household Products,Household and Personal Products
43,UPS,65872.0,4910.0,346415,Transportation,"Mail, Package, and Freight Delivery"
44,PepsiCo,63525.0,4857.0,263000,"Food, Beverages & Tobacco",Food Consumer Products
46,DowDuPont,62683.0,1460.0,98000,Chemicals,Chemicals
47,Archer Daniels Midland,60828.0,1595.0,31300,"Food, Beverages & Tobacco",Food Production
49,FedEx,60319.0,2997.0,357000,Transportation,"Mail, Package, and Freight Delivery"
50,United Technologies,59837.0,4552.0,204700,Aerospace & Defense,Aerospace and Defense
54,Disney,55137.0,8980.0,199000,Media,Entertainment
64,Caterpillar,45462.0,754.0,98400,Industrials,Construction and Farm Machinery
88,Nike,34350.0,4240.0,74400,Apparel,Apparel
97,Time Warner,31271.0,5247.0,26000,Media,Entertainment
123,International Paper,23302.0,2144.0,56000,Materials,"Packaging, Containers"
126,Marriott International,22894.0,1372.0,177000,"Hotels, Restaurants & Leisure","Hotels, Casinos, Resorts"
130,McDonalds,22820.0,5192.3,235000,"Hotels, Restaurants & Leisure",Food Services
142,ManpowerGroup,21034.0,545.4,29000,Business Services,Temporary Help
150,Nucor,20252.0,1318.7,25100,Materials,Metals
152,Fluor,19521.0,191.4,56706,Engineering & Construction,"Engineering, Construction"
160,Visa,18358.0,6699.0,15000,Business Services,Financial Data Services
162,Kimberly-Clark,18259.0,2278.0,42000,Household Products,Household and Personal Products
163,AECOM,18203.0,339.4,87000,Engineering & Construction,"Engineering, Construction"
189,Sherwin-Williams,14984.0,1772.3,52695,Chemicals,Chemicals
241,VF,12400.0,614.9,69000,Apparel,Apparel

In [18]:
sectors.tail(2)

,Company,Revenues,Profits,Employees,Sector,Industry
520,Telephone & Data Systems,5044.0,153.0,9900,Telecommunications,Telecommunications
835,Columbia Sportswear,2466.0,105.1,6188,Apparel,Apparel
839,GNC Holdings,2453.0,-148.9,11500,Food & Drug Stores,Food and Drug Stores
861,Wolverine World Wide,2350.0,0.3,3700,Apparel,Apparel
900,Snyders-Lance,2227.0,148.5,5900,"Food, Beverages & Tobacco",Food Consumer Products
907,Zayo Group Holdings,2200.0,85.7,3794,Telecommunications,Telecommunications
920,LCI Industries,2148.0,132.9,9852,Motor Vehicles & Parts,Motor Vehicles and Parts
937,Universal,2071.0,106.3,24000,"Food, Beverages & Tobacco",Tobacco
940,Tower International,2066.0,47.6,7600,Motor Vehicles & Parts,Motor Vehicles and Parts
941,Freds,2064.0,-140.3,7324,Food & Drug Stores,Food and Drug Stores
942,Foundation Building Materials,2061.0,82.5,3782,Wholesalers,Wholesalers: Diversified
946,Central Garden & Pet,2055.0,78.8,4050,Household Products,Household and Personal Products
947,Matson,2047.0,232.0,1947,Transportation,Shipping
957,Griffon,1986.0,14.9,4700,Materials,"Building Materials, Glass"
961,Deluxe,1966.0,230.2,5886,Media,"Publishing, Printing"
963,Kraton,1960.0,97.5,1931,Chemicals,Chemicals
965,Marriott Vacations Worldwide,1952.0,226.8,11000,"Hotels, Restaurants & Leisure","Hotels, Casinos, Resorts"
966,SPX FLOW,1952.0,46.4,7000,Industrials,Industrial Machinery
967,ACCO Brands,1949.0,131.7,6620,Household Products,"Home Equipment, Furnishings"
968,Echo Global Logistics,1943.0,12.6,2453,Transportation,Transportation and Logistics
972,TransUnion,1934.0,441.2,5100,Business Services,Financial Data Services
974,Summit Materials,1933.0,121.8,6000,Materials,"Building Materials, Glass"
975,Engility Holdings,1932.0,-35.2,8700,Aerospace & Defense,Aerospace and Defense
978,Stepan,1925.0,91.6,2096,Chemicals,Chemicals
980,Cimarex Energy,1918.0,494.3,910,Energy,"Mining, Crude-Oil Production"
981,Rexnord,1918.0,74.1,8000,Industrials,Industrial Machinery
982,Beazer Homes USA,1916.0,31.8,1100,Engineering & Construction,Homebuilders
983,MKS Instruments,1916.0,339.1,4923,Technology,Semiconductors and Other Electronic Components
984,Vail Resorts,1907.0,210.6,20150,"Hotels, Restaurants & Leisure","Hotels, Casinos, Resorts"
986,TopBuild,1906.0,158.1,8400,Engineering & Construction,"Engineering, Construction"
987,Brown & Brown,1881.0,399.6,8491,Financials,Insurance: Property and Casualty (Stock)
988,Aerojet Rocketdyne Holdings,1877.0,-9.2,5157,Aerospace & Defense,Aerospace and Defense
989,Barnes & Noble Education,1874.0,5.4,13375,Retailing,Specialty Retailers: Other
990,Superior Energy Services,1874.0,-205.9,6400,Energy,"Oil and Gas Equipment, Services"
991,VeriFone Systems,1871.0,-173.8,5600,Technology,Financial Data Services
992,Childrens Place,1870.0,84.7,9800,Retailing,Specialty Retailers: Apparel
993,Tribune Media,1867.0,194.1,6000,Media,Entertainment
995,SiteOne Landscape Supply,1862.0,54.6,3664,Wholesalers,Wholesalers: Diversified
996,Charles River Laboratories Intl,1858.0,123.4,11800,Health Care,Health Care: Pharmacy and Other Services
997,CoreLogic,1851.0,152.2,5900,Business Services,Financial Data Services
998,Ensign Group,1849.0,40.5,21301,Health Care,Health Care: Medical Facilities
999,HCP,1848.0,414.2,190,Financials,Real estate

In [20]:
sectors.get_group('Apparel')

                  Company  Revenues  Profits  Employees   Sector Industry
88                   Nike   34350.0   4240.0      74400  Apparel  Apparel
241                    VF   12400.0    614.9      69000  Apparel  Apparel
331                   PVH    8915.0    537.8      28050  Apparel  Apparel
420          Ralph Lauren    6653.0    -99.3      18250  Apparel  Apparel
432           Hanesbrands    6478.0     61.9      67200  Apparel  Apparel
526          Under Armour    4977.0    -48.3      11350  Apparel  Apparel
529          Levi Strauss    4904.0    281.4      13800  Apparel  Apparel
554              Tapestry    4488.3    591.0      12450  Apparel  Apparel
587       Skechers U.S.A.    4181.0    179.2       8150  Apparel  Apparel
678               Carters    3400.0    302.8      20900  Apparel  Apparel
766   G-III Apparel Group    2807.0     62.1       9961  Apparel  Apparel
774          Fossil Group    2788.0   -478.2      12300  Apparel  Apparel
835   Columbia Sportswear    2466.0    105.1       6188  Apparel  Apparel
861  Wolverine World Wide    2350.0      0.3       3700  Apparel  Apparel

In [21]:
sectors.mean(numeric_only=True)

                                   Revenues      Profits      Employees
Sector
Aerospace & Defense            15353.400000  1069.340000   40404.960000
Apparel                         7225.521429   453.621429   25407.071429
Business Services               5963.962264   701.494340   30075.452830
Chemicals                       7610.636364   620.454545   14364.242424
Energy                         14425.300935   805.373585    9170.158879
Engineering & Construction      6399.333333   263.740741   15583.148148
Financials                     15757.935484  1704.861290   22581.412903
Food &  Drug Stores            33789.000000   703.358333  116506.166667
Food, Beverages & Tobacco      13790.054054  1483.851351   29170.702703
Health Care                    21239.315493  1306.916901   41847.732394
Hotels, Restaurants & Leisure   6916.346154   819.442308   88628.346154
Household Products              8277.850000   990.242857   24103.428571
Industrials                    10615.102041   390.087755   31961.428571
Materials                       6184.400000   305.120000   14527.800000
Media                           9219.496000   920.796000   21839.400000
Motor Vehicles & Parts         22817.631579   361.110526   49662.210526
Retailing                      21874.714286   723.470130   88320.233766
Technology                     13347.789320  1743.959804   31036.961165
Telecommunications             46695.900000  9196.580000   78560.900000
Transportation                 11379.000000  1324.007500   41302.825000
Wholesalers                    20185.204545   355.850000   16913.068182

In [22]:
sectors.sum(numeric_only=True)

                                Revenues   Profits  Employees
Sector
Aerospace & Defense             383835.0   26733.5    1010124
Apparel                         101157.3    6350.7     355699
Business Services               316090.0   37179.2    1593999
Chemicals                       251151.0   20475.0     474020
Energy                         1543507.2   85369.6     981207
Engineering & Construction      172782.0    7121.0     420745
Financials                     2442480.0  264253.5    3500119
Food &  Drug Stores             405468.0    8440.3    1398074
Food, Beverages & Tobacco       510232.0   54902.5    1079316
Health Care                    1507991.4   92791.1    2971189
Hotels, Restaurants & Leisure   179825.0   21305.5    2304337
Household Products              231779.8   27726.8     674896
Industrials                     520140.0   19114.3    1566110
Materials                       278298.0   13730.4     653751
Media                           230487.4   23019.9     545985
Motor Vehicles & Parts          433535.0    6861.1     943582
Retailing                      1684353.0   55707.2    6800658
Technology                     1374822.3  177883.9    3196807
Telecommunications              466959.0   91965.8     785609
Transportation                  455160.0   52960.3    1652113
Wholesalers                     888149.0   15657.4     744175

In [23]:
sectors.min(numeric_only=True)

                               Revenues  Profits  Employees
Sector
Aerospace & Defense              1877.0    -74.0       5157
Apparel                          2350.0   -478.2       3700
Business Services                1851.0   -557.1       2338
Chemicals                        1925.0   -296.2       1931
Energy                           1874.0  -5723.0        593
Engineering & Construction       1906.0   -332.2       1100
Financials                       1848.0  -6798.0        152
Food &  Drug Stores              2064.0   -373.3       7324
Food, Beverages & Tobacco        2071.0   -286.2       1819
Health Care                      1849.0  -2459.0       2298
Hotels, Restaurants & Leisure    1907.0   -375.0       8600
Household Products               1949.0  -1053.8       4050
Industrials                      1918.0  -5786.0       4125
Materials                        1933.0   -258.0        126
Media                            1867.0   -738.0       2039
Motor Vehicles & Parts           2066.0  -3864.0       2700
Retailing                        1870.0  -1067.3       2505
Technology                       1871.0  -3728.0       2100
Telecommunications               2200.0  -2116.6       3794
Transportation                   1943.0   -106.7       1273
Wholesalers                      1862.0   -267.0        981

In [24]:
sectors.max(numeric_only=True)

                               Revenues  Profits  Employees
Sector
Aerospace & Defense             93392.0   8197.0     204700
Apparel                         34350.0   4240.0      74400
Business Services               21034.0   6699.0     215000
Chemicals                       62683.0   3000.4      98000
Energy                         244363.0  19710.0      71200
Engineering & Construction      19521.0   1038.4      87000
Financials                     242137.0  44940.0     377000
Food &  Drug Stores            122662.0   4078.0     449000
Food, Beverages & Tobacco       63525.0  10999.0     263000
Health Care                    201159.0  21308.0     260000
Hotels, Restaurants & Leisure   22894.0   5192.3     450000
Household Products              66217.0  15326.0      95000
Industrials                    122274.0   4858.0     313000
Materials                       23302.0   2144.0      56000
Media                           55137.0   8980.0     199000
Motor Vehicles & Parts         157311.0   7602.0     202000
Retailing                      500343.0   9862.0    2300000
Technology                     229234.0  48351.0     397800
Telecommunications             160546.0  30101.0     254000
Transportation                  65872.0  10712.0     357000
Wholesalers                    198533.0   5070.0     113600

In [25]:
sectors['Profits'].max(numeric_only=True)

Sector
Aerospace & Defense               8197.0
Apparel                           4240.0
Business Services                 6699.0
Chemicals                         3000.4
Energy                           19710.0
Engineering & Construction        1038.4
Financials                       44940.0
Food &  Drug Stores               4078.0
Food, Beverages & Tobacco        10999.0
Health Care                      21308.0
Hotels, Restaurants & Leisure     5192.3
Household Products               15326.0
Industrials                       4858.0
Materials                         2144.0
Media                             8980.0
Motor Vehicles & Parts            7602.0
Retailing                         9862.0
Technology                       48351.0
Telecommunications               30101.0
Transportation                   10712.0
Wholesalers                       5070.0
Name: Profits, dtype: float64

In [26]:
sectors['Profits'].min(numeric_only=True)

Sector
Aerospace & Defense               -74.0
Apparel                          -478.2
Business Services                -557.1
Chemicals                        -296.2
Energy                          -5723.0
Engineering & Construction       -332.2
Financials                      -6798.0
Food &  Drug Stores              -373.3
Food, Beverages & Tobacco        -286.2
Health Care                     -2459.0
Hotels, Restaurants & Leisure    -375.0
Household Products              -1053.8
Industrials                     -5786.0
Materials                        -258.0
Media                            -738.0
Motor Vehicles & Parts          -3864.0
Retailing                       -1067.3
Technology                      -3728.0
Telecommunications              -2116.6
Transportation                   -106.7
Wholesalers                      -267.0
Name: Profits, dtype: float64

In [28]:
sectors.agg({"Revenues": "sum", "Profits": "mean", "Employees": "min"})

                                Revenues      Profits  Employees
Sector
Aerospace & Defense             383835.0  1069.340000       5157
Apparel                         101157.3   453.621429       3700
Business Services               316090.0   701.494340       2338
Chemicals                       251151.0   620.454545       1931
Energy                         1543507.2   805.373585        593
Engineering & Construction      172782.0   263.740741       1100
Financials                     2442480.0  1704.861290        152
Food &  Drug Stores             405468.0   703.358333       7324
Food, Beverages & Tobacco       510232.0  1483.851351       1819
Health Care                    1507991.4  1306.916901       2298
Hotels, Restaurants & Leisure   179825.0   819.442308       8600
Household Products              231779.8   990.242857       4050
Industrials                     520140.0   390.087755       4125
Materials                       278298.0   305.120000        126
Media                           230487.4   920.796000       2039
Motor Vehicles & Parts          433535.0   361.110526       2700
Retailing                      1684353.0   723.470130       2505
Technology                     1374822.3  1743.959804       2100
Telecommunications              466959.0  9196.580000       3794
Transportation                  455160.0  1324.007500       1273
Wholesalers                     888149.0   355.850000        981

In [30]:
def get_largest_profits(df):
    return df.nlargest(1, 'Profits')
sectors.apply(get_largest_profits,include_groups=False)

,,Company,Revenues,Profits,Employees,Industry
Sector,,,,,,
Aerospace & Defense,26,Boeing,93392.0,8197.0,140800,Aerospace and Defense
Apparel,88,Nike,34350.0,4240.0,74400,Apparel
Business Services,160,Visa,18358.0,6699.0,15000,Financial Data Services
Chemicals,344,Air Products & Chemicals,8442.0,3000.4,15150,Chemicals
Energy,1,Exxon Mobil,244363.0,19710.0,71200,Petroleum Refining
Engineering & Construction,210,D.R. Horton,14091.0,1038.4,7735,Homebuilders
Financials,2,Berkshire Hathaway,242137.0,44940.0,377000,Insurance: Property and Casualty (Stock)
Food & Drug Stores,18,Walgreens Boots Alliance,118214.0,4078.0,290000,Food and Drug Stores
"Food, Beverages & Tobacco",113,Kraft Heinz,26232.0,10999.0,39000,Food Consumer Products
Health Care,56,Pfizer,52546.0,21308.0,90200,Pharmaceuticals
"Hotels, Restaurants & Leisure",130,McDonalds,22820.0,5192.3,235000,Food Services
Household Products,41,Procter & Gamble,66217.0,15326.0,95000,Household and Personal Products
Industrials,96,3M,31657.0,4858.0,91536,Miscellaneous
Materials,123,International Paper,23302.0,2144.0,56000,"Packaging, Containers"
Media,54,Disney,55137.0,8980.0,199000,Entertainment
Motor Vehicles & Parts,10,Ford Motor,156776.0,7602.0,202000,Motor Vehicles and Parts
Retailing,0,Walmart,500343.0,9862.0,2300000,General Merchandisers
Technology,3,Apple,229234.0,48351.0,123000,"Computers, Office Equipment"
Telecommunications,15,Verizon,126034.0,30101.0,155400,Telecommunications
Transportation,140,Union Pacific,21240.0,10712.0,41992,Railroads
Wholesalers,5,McKesson,198533.0,5070.0,64500,Wholesalers: Health Care

In [32]:
sector = ft.groupby(['Sector','Industry'])
sector.size()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            25
Apparel              Apparel                                          14
Business Services    Advertising, marketing                            2
                     Diversified Outsourcing Services                 14
                     Education                                         2
                                                                      ..
Transportation       Trucking, Truck Leasing                          11
Wholesalers          Wholesalers: Diversified                         24
                     Wholesalers: Electronics and Office Equipment     8
                     Wholesalers: Food and Grocery                     6
                     Wholesalers: Health Care                          6
Length: 82, dtype: int64

In [36]:
sector.get_group(('Business Services','Education'))

,Company,Revenues,Profits,Employees,Sector,Industry
567,Laureate Education,4378.0,91.5,54500,Business Services,Education
810,Graham Holdings,2592.0,302.0,16153,Business Services,Education